Traceback (most recent call last):
  File "./sync", line 15, in <module>
    emailAddress = os.environ["NOTE_SYNC_MAIL"]
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'NOTE_SYNC_MAIL'
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...
Saving file /root/huy/bookmarks/index.html...
Wrote /root/huy/bookmarks/index.html
